export const guides = [
  {
    slug: 'fix-leaky-faucet',
    title: 'Fix a Leaky Faucet',
    description: 'Stop that drip and save up to $200/year on your water bill. No plumber needed.',
    category: 'plumbing',
    duration: '45 min',
    cost: '$15–30',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 312,
    premium: false,
    contractorCost: 175,
    diyCost: 22,
    creator: {
      name: 'Rosco Reviews',
      subscribers: '22.3K',
      channelUrl: 'https://www.youtube.com/@RoscoReviews',
      videoUrl: 'https://youtu.be/dyx5VgsVM6A',
    },
    steps: [
      { title: 'Shut off the water supply', body: 'Turn the valves under the sink clockwise until fully closed. Test by turning on the tap — no water should flow.' },
      { title: 'Remove the faucet handle', body: 'Unscrew the decorative cap and the handle screw. Pull the handle straight up to remove.' },
      { title: 'Replace the cartridge or O-rings', body: 'Take the old part to the hardware store to match it. Install the new one in the same orientation.' },
      { title: 'Reassemble and test', body: 'Reverse the disassembly steps, turn the water back on slowly, and check for leaks.' },
    ],
    materials: [
      { name: 'Replacement cartridge', price: '$12–18', affiliate: true },
      { name: 'O-ring kit', price: '$4', affiliate: true },
      { name: 'Adjustable wrench', price: '$14', affiliate: true },
    ],
  },
  {
    slug: 'unclog-drain',
    title: 'Unclog a Slow Drain',
    description: 'Clear hair and soap buildup from bathroom drains in minutes using tools you already have.',
    category: 'plumbing',
    duration: '20 min',
    cost: '$0–10',
    difficulty: 'Beginner',
    rating: 4.7,
    reviews: 518,
    premium: false,
    contractorCost: 120,
    diyCost: 5,
    creator: {
      name: 'Reluctant DIYers',
      subscribers: '33.7K',
      channelUrl: 'https://www.youtube.com/@ReluctantDIYers',
      videoUrl: 'https://youtu.be/2zNTMHypIlk',
    },
    steps: [
      { title: 'Remove the drain cover', body: 'Unscrew or pop out the drain stopper. Have a bag ready for debris.' },
      { title: 'Use a drain snake or zip-it tool', body: 'Insert the tool and rotate to catch the clog. Pull out slowly.' },
      { title: 'Flush with hot water', body: 'Run the hottest tap water for 2 minutes to clear residue.' },
    ],
    materials: [
      { name: 'Zip-it drain cleaning tool', price: '$4', affiliate: true },
      { name: 'Rubber gloves', price: '$5', affiliate: true },
    ],
  },
  {
    slug: 'change-furnace-filter',
    title: 'Change Your Furnace Filter',
    description: 'Improve air quality and prevent $500+ HVAC repairs with a 5-minute quarterly task.',
    category: 'hvac',
    duration: '5 min',
    cost: '$10–25',
    difficulty: 'Beginner',
    rating: 4.9,
    reviews: 724,
    premium: false,
    contractorCost: 85,
    diyCost: 15,
    creator: { name: 'HVAC Guide', subscribers: '95K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Find your filter slot', body: 'Usually located on the return air duct or inside the furnace cabinet. Check your manual if unsure.' },
      { title: 'Note the filter size', body: 'Check the edges of the old filter for dimensions (e.g. 16x25x1).' },
      { title: 'Install the new filter', body: 'Slide in with the arrow pointing toward the furnace. Seal the slot closed.' },
    ],
    materials: [
      { name: 'MERV-8 furnace filter (4-pack)', price: '$22', affiliate: true },
    ],
  },
  {
    slug: 'fix-squeaky-floor',
    title: 'Fix a Squeaky Floor',
    description: 'Silence annoying creaks in hardwood or subfloor without removing any boards.',
    category: 'carpentry',
    duration: '30 min',
    cost: '$5–20',
    difficulty: 'Beginner',
    rating: 4.6,
    reviews: 201,
    premium: false,
    contractorCost: 150,
    diyCost: 12,
    creator: { name: 'DIY Pete', subscribers: '320K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Find the squeak', body: 'Walk the area slowly and mark squeaky spots with painter\'s tape.' },
      { title: 'Drive screws through the subfloor', body: 'Use a drill to drive 1.5" drywall screws at an angle into the joist, pulling the subfloor tight.' },
      { title: 'Fill screw holes', body: 'Use wood filler matched to your floor color and sand smooth when dry.' },
    ],
    materials: [
      { name: 'Squeak-Ender kit', price: '$18', affiliate: true },
      { name: 'Wood filler', price: '$7', affiliate: true },
    ],
  },
  {
    slug: 'replace-light-switch',
    title: 'Replace a Light Switch',
    description: 'Swap out a broken or outdated switch in 20 minutes. Covers single-pole and 3-way switches.',
    category: 'electrical',
    duration: '20 min',
    cost: '$5–15',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviews: 389,
    premium: true,
    contractorCost: 130,
    diyCost: 10,
    creator: {
      name: 'Colton Crump DIY',
      subscribers: '21.4K',
      channelUrl: 'https://www.youtube.com/@ColtonCrumpDIY',
      // videoUrl intentionally omitted: creator has embedding disabled on
      // their videos. Sidebar still shows them as the guide creator with a
      // link to their channel; we'd swap in an embeddable video once they
      // enable embedding (or pick a different creator for this guide).
    },
    steps: [
      { title: 'Kill the breaker', body: 'Turn off the circuit at your breaker panel. Use a non-contact voltage tester to confirm power is off.' },
      { title: 'Remove the old switch', body: 'Unscrew the cover plate and switch. Take a photo of the wiring before disconnecting.' },
      { title: 'Connect the new switch', body: 'Match wires to the same terminals. Tighten screws firmly.' },
      { title: 'Restore power and test', body: 'Flip the breaker back on and test the switch.' },
    ],
    materials: [
      { name: 'Single-pole switch', price: '$5', affiliate: true },
      { name: 'Non-contact voltage tester', price: '$18', affiliate: true },
      { name: 'Flathead & Phillips screwdrivers', price: '$12', affiliate: true },
    ],
  },
  {
    slug: 'install-laminate-flooring',
    title: 'Install Laminate Flooring',
    description: 'Transform a room with a floating floor installation. No glue, no nails — click-together system.',
    category: 'flooring',
    duration: '1–2 days',
    cost: '$200–600',
    difficulty: 'Intermediate',
    rating: 4.5,
    reviews: 156,
    premium: true,
    contractorCost: 900,
    diyCost: 350,
    creator: {
      name: 'Thou Shalt DIY',
      subscribers: '13.4K',
      channelUrl: 'https://www.youtube.com/@ThouShaltDIY',
      videoUrl: 'https://youtu.be/2iM76oLzKqY',
    },
    steps: [
      { title: 'Acclimate the flooring', body: 'Let planks sit in the room for 48 hours so they adjust to temperature and humidity.' },
      { title: 'Prepare the subfloor', body: 'Remove old flooring, fill low spots, and install foam underlayment.' },
      { title: 'Lay the first row', body: 'Start against the longest straight wall, leaving a 1/4" expansion gap.' },
      { title: 'Click and lock rows', body: 'Angle each plank into the previous row and snap down. Stagger end joints by at least 12".' },
      { title: 'Install baseboards', body: 'Cover the expansion gap with baseboards. Do not nail through the flooring.' },
    ],
    materials: [
      { name: 'Laminate flooring (measure your sq ft + 10%)', price: '$1.50–3/sq ft', affiliate: true },
      { name: 'Foam underlayment', price: '$0.25/sq ft', affiliate: true },
      { name: 'Pull bar & tapping block set', price: '$18', affiliate: true },
      { name: 'Spacers', price: '$8', affiliate: true },
    ],
  },
  {
    slug: 'paint-a-room',
    title: 'Paint a Room Like a Pro',
    description: 'Get a smooth, drip-free finish with the right prep, tools, and technique.',
    category: 'painting',
    duration: '1 day',
    cost: '$80–150',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 603,
    premium: false,
    contractorCost: 600,
    diyCost: 110,
    creator: { name: 'Paint Life', subscribers: '210K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Prep the room', body: 'Move furniture, remove switch plates, and lay drop cloths.' },
      { title: 'Patch and sand', body: 'Fill nail holes and cracks with spackle. Sand smooth when dry.' },
      { title: "Cut in edges", body: "Use a 2\" angled brush to paint a 3\" border along ceilings, trim, and corners." },
      { title: 'Roll the walls', body: 'Use a 3/8" nap roller in a W pattern, working top to bottom. Apply 2 coats.' },
    ],
    materials: [
      { name: 'Interior paint (1 gal per 350–400 sq ft)', price: '$35–55/gal', affiliate: true },
      { name: '2" angled brush', price: '$12', affiliate: true },
      { name: '3/8" nap roller + frame', price: '$18', affiliate: true },
      { name: "Painter's tape", price: '$8', affiliate: true },
    ],
  },
  {
    slug: 'fix-running-toilet',
    title: 'Fix a Running Toilet',
    description: 'A running toilet wastes 200 gallons a day. Fix it in 30 minutes with a $12 kit.',
    category: 'plumbing',
    duration: '30 min',
    cost: '$12–30',
    difficulty: 'Beginner',
    rating: 4.9,
    reviews: 445,
    premium: false,
    contractorCost: 150,
    diyCost: 20,
    creator: { name: 'Fix It With Rick', subscribers: '240K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Open the tank', body: 'Remove the lid and look inside. The flapper, float, or fill valve is usually the culprit.' },
      { title: 'Check the flapper', body: 'Push down on the flapper. If the running stops, the flapper needs replacing.' },
      { title: 'Replace the flapper', body: 'Unhook the old flapper from the overflow tube ears and snap on the new one.' },
      { title: 'Adjust the float', body: 'The water level should be 1" below the overflow tube. Bend or adjust the float arm.' },
    ],
    materials: [
      { name: 'Universal flapper', price: '$8', affiliate: true },
      { name: 'Fill valve kit', price: '$14', affiliate: true },
    ],
  },
  {
    slug: 'caulk-bathtub',
    title: 'Recaulk a Bathtub',
    description: 'Remove old, moldy caulk and apply a clean bead that lasts years — not months.',
    category: 'plumbing',
    duration: '2 hrs + drying',
    cost: '$15–25',
    difficulty: 'Beginner',
    rating: 4.6,
    reviews: 287,
    premium: false,
    contractorCost: 120,
    diyCost: 18,
    creator: { name: 'Home Repair Tutor', subscribers: '180K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Remove old caulk', body: 'Use a caulk remover tool or utility knife to cut and peel out all old caulk. This takes patience.' },
      { title: 'Clean and dry thoroughly', body: 'Spray with mold-killing cleaner, wipe clean, then wait 24 hours for full drying.' },
      { title: 'Apply new caulk', body: 'Cut the tip at 45°, apply steady pressure in one continuous bead along the joint.' },
      { title: 'Smooth and cure', body: 'Dip a finger in water and run along the bead. Do not use the tub for 24 hours.' },
    ],
    materials: [
      { name: 'Silicone tub & tile caulk', price: '$8', affiliate: true },
      { name: 'Caulk removal tool', price: '$7', affiliate: true },
    ],
  },
  {
    slug: 'install-ceiling-fan',
    title: 'Install a Ceiling Fan',
    description: 'Replace an old light fixture with a ceiling fan. Can cut cooling costs by 30%.',
    category: 'electrical',
    duration: '2 hrs',
    cost: '$80–200',
    difficulty: 'Intermediate',
    rating: 4.5,
    reviews: 198,
    premium: true,
    contractorCost: 250,
    diyCost: 140,
    creator: { name: 'Sparky Channel', subscribers: '145K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Turn off the breaker', body: 'Kill power at the panel and verify with a voltage tester.' },
      { title: 'Remove the old fixture', body: 'Disconnect wires and remove the old box. Install a fan-rated ceiling box.' },
      { title: 'Assemble the fan', body: 'Follow the included instructions. Attach the mounting bracket and canopy.' },
      { title: 'Wire and mount', body: 'Match wire colors (black to black, white to white, ground to green/bare). Snap the canopy up.' },
      { title: 'Attach blades and test', body: 'Install blade brackets and blades. Restore power and test all speeds.' },
    ],
    materials: [
      { name: 'Ceiling fan (your choice)', price: '$60–150', affiliate: true },
      { name: 'Fan-rated ceiling box', price: '$14', affiliate: true },
    ],
  },
  {
    slug: 'winterize-sprinklers',
    title: 'Winterize Your Sprinkler System',
    description: 'Blow out your irrigation lines before the first freeze to avoid cracked pipes.',
    category: 'landscaping',
    duration: '1 hr',
    cost: '$0–30',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviews: 143,
    premium: true,
    contractorCost: 80,
    diyCost: 0,
    creator: { name: 'Lawn & Order', subscribers: '72K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Shut off the water supply', body: 'Close the main irrigation shutoff valve.' },
      { title: 'Rent a compressor', body: 'You need a 20–50 CFM compressor (most home compressors are too small). Many equipment rental shops carry them.' },
      { title: 'Blow out each zone', body: 'Connect to the blow-out port, set controller to Zone 1, and blow for 2 minutes at 50 PSI max.' },
      { title: 'Drain and insulate', body: 'Drain any remaining water and insulate above-ground components.' },
    ],
    materials: [
      { name: 'Compressor rental (or buy an adapter)', price: '$30/day rental', affiliate: false },
      { name: 'Pipe insulation wrap', price: '$8', affiliate: true },
    ],
  },
  {
    slug: 'fix-drywall-hole',
    title: 'Patch a Drywall Hole',
    description: 'Make doorknob holes and other damage disappear with a smooth, paintable patch.',
    category: 'carpentry',
    duration: '2 hrs + drying',
    cost: '$15–30',
    difficulty: 'Beginner',
    rating: 4.7,
    reviews: 334,
    premium: false,
    contractorCost: 140,
    diyCost: 22,
    creator: { name: 'DIY Pete', subscribers: '320K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Cut a clean opening', body: 'Use a drywall saw to make a square around the damaged area.' },
      { title: 'Add backing', body: 'Cut a piece of wood to span the hole and screw it in from inside.' },
      { title: 'Cut and attach a patch', body: 'Cut a drywall patch to fit, screw to the backing, tape the seams.' },
      { title: 'Apply joint compound', body: 'Skim 3 thin coats, sanding lightly between each. Feather edges wide.' },
    ],
    materials: [
      { name: 'Drywall patch kit', price: '$14', affiliate: true },
      { name: 'Joint compound', price: '$8', affiliate: true },
      { name: 'Drywall tape', price: '$5', affiliate: true },
      { name: 'Sanding sponge', price: '$6', affiliate: true },
    ],
  },
  {
    slug: 'clean-shower-head',
    title: 'Clean a Clogged Shower Head',
    description: 'Restore water pressure in 20 minutes with a supply you already own. No plumber, no new fixture.',
    category: 'plumbing',
    duration: '20 min + overnight soak',
    cost: '$0–5',
    difficulty: 'Beginner',
    rating: 4.9,
    reviews: 612,
    premium: false,
    contractorCost: 95,
    diyCost: 3,
    creator: { name: 'Home Repair Tutor', subscribers: '180K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Unscrew the shower head', body: 'Turn counter-clockwise by hand. If stuck, wrap a rag around it and use pliers gently.' },
      { title: 'Soak in vinegar', body: 'Submerge the shower head in a bowl of white vinegar. Leave overnight for heavy calcium buildup.' },
      { title: 'Scrub and rinse', body: 'Scrub the face and nozzles with an old toothbrush. Flush with hot water until it runs clear.' },
      { title: 'Wrap threads and reinstall', body: 'Wrap the shower arm threads with plumber\'s tape (2–3 wraps, clockwise). Hand-tighten only.' },
    ],
    materials: [
      { name: 'White vinegar (1 gal)', price: '$3', affiliate: true },
      { name: "Plumber's tape", price: '$2', affiliate: true },
    ],
  },
  {
    slug: 'fix-garbage-disposal',
    title: 'Fix a Jammed Garbage Disposal',
    description: 'The hum-but-no-grind problem is almost always a jam. Clear it yourself in 10 minutes.',
    category: 'plumbing',
    duration: '10 min',
    cost: '$0',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 478,
    premium: false,
    contractorCost: 150,
    diyCost: 0,
    creator: { name: 'Fix It With Rick', subscribers: '240K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Cut the power', body: 'Unplug the disposal under the sink, or flip the breaker. Never reach into a disposal with power on.' },
      { title: 'Find the hex socket underneath', body: 'The bottom of every disposal has a 1/4" hex hole. The Allen wrench for it often comes taped to the unit.' },
      { title: 'Rock the impeller free', body: 'Insert the Allen wrench and rotate back and forth. You\'ll feel the jam release.' },
      { title: 'Clear debris and reset', body: 'Use tongs (never fingers) to remove whatever caused the jam. Press the red reset button on the bottom.' },
      { title: 'Restore power and test', body: 'Plug back in, run cold water, and switch on. Should grind normally.' },
    ],
    materials: [
      { name: '1/4" Allen wrench', price: '$0 (usually included)', affiliate: false },
      { name: 'Kitchen tongs', price: '$0 (already have)', affiliate: false },
    ],
  },
  {
    slug: 'replace-outlet',
    title: 'Replace an Electrical Outlet',
    description: 'Swap a worn or damaged outlet for about $3 in parts. Covers standard duplex replacement.',
    category: 'electrical',
    duration: '30 min',
    cost: '$3–10',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviews: 241,
    premium: true,
    contractorCost: 140,
    diyCost: 5,
    creator: { name: 'Sparky Channel', subscribers: '145K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Turn off the breaker', body: 'Find the breaker for that outlet and flip it off. Confirm with a non-contact voltage tester at the outlet.' },
      { title: 'Remove the cover and outlet', body: 'Unscrew the cover plate. Unscrew the outlet from the box and pull it out gently.' },
      { title: 'Photograph the wiring', body: 'Before disconnecting anything, take a clear photo of how wires are attached. This is your insurance.' },
      { title: 'Transfer wires to the new outlet', body: 'Black (hot) to brass screw, white (neutral) to silver screw, bare/green (ground) to green screw.' },
      { title: 'Mount, cover, and test', body: 'Screw the outlet back in, reattach the cover, restore power, test with a plug-in tester.' },
    ],
    materials: [
      { name: 'Standard 15A duplex outlet', price: '$3', affiliate: true },
      { name: 'Non-contact voltage tester', price: '$18', affiliate: true },
      { name: 'Outlet tester', price: '$10', affiliate: true },
    ],
  },
  {
    slug: 'install-gfci',
    title: 'Install a GFCI Outlet',
    description: 'Required by code in kitchens, bathrooms, and outdoors. Protects against shock and is straightforward DIY.',
    category: 'electrical',
    duration: '45 min',
    cost: '$15–25',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviews: 189,
    premium: true,
    contractorCost: 160,
    diyCost: 18,
    creator: { name: 'Sparky Channel', subscribers: '145K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Kill the breaker', body: 'Verify with a voltage tester at the existing outlet.' },
      { title: 'Identify line vs load wires', body: 'GFCI outlets have LINE terminals (power in) and LOAD terminals (power out to other outlets). Check with a tester to find the LINE.' },
      { title: 'Wire the LINE terminals', body: 'Hot (black) and neutral (white) from incoming power go to the LINE side. Ground goes to the green screw.' },
      { title: 'Wire LOAD only if needed', body: 'If other downstream outlets depend on this one, connect their wires to LOAD terminals. Otherwise, cap them off.' },
      { title: 'Test', body: 'Restore power, press TEST (should cut power), press RESET (should restore). Plug in a tester to verify.' },
    ],
    materials: [
      { name: 'GFCI outlet (15A or 20A to match circuit)', price: '$16', affiliate: true },
      { name: 'Non-contact voltage tester', price: '$18', affiliate: true },
    ],
  },
  {
    slug: 'install-smart-thermostat',
    title: 'Install a Smart Thermostat',
    description: 'Save 10–15% on heating/cooling with a programmable thermostat. Most installs are 30 minutes.',
    category: 'electrical',
    duration: '30 min',
    cost: '$80–250',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 523,
    premium: false,
    contractorCost: 175,
    diyCost: 130,
    creator: { name: 'HVAC Guide', subscribers: '95K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Turn off power at the breaker', body: 'Find the breaker labeled "furnace" or "HVAC" and flip it off.' },
      { title: 'Remove the old thermostat', body: 'Pull off the faceplate, then unscrew the backplate. Photograph the wiring before disconnecting.' },
      { title: 'Check for a C-wire', body: 'Most smart thermostats need a "common" wire. If you don\'t have one, use the included adapter or contact the manufacturer for help.' },
      { title: 'Mount the new backplate', body: 'Thread wires through and screw to the wall. Use the included level if your wall isn\'t perfectly flat.' },
      { title: 'Wire to the new thermostat', body: 'Match each wire to the labeled terminal (R, W, Y, G, C) following your photo and the new thermostat\'s diagram.' },
      { title: 'Snap on and set up', body: 'Restore power and follow the on-screen setup. Connect to Wi-Fi and your phone app.' },
    ],
    materials: [
      { name: 'Smart thermostat (Nest, Ecobee, or Honeywell)', price: '$100–250', affiliate: true },
      { name: 'Small flathead screwdriver', price: '$6', affiliate: true },
    ],
  },
  {
    slug: 'clean-ac-coils',
    title: 'Clean Your Outdoor AC Coils',
    description: 'Dirty condenser coils make your AC work twice as hard. 30 minutes of spring maintenance saves hundreds.',
    category: 'hvac',
    duration: '30 min',
    cost: '$10–15',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 267,
    premium: false,
    contractorCost: 180,
    diyCost: 12,
    creator: { name: 'HVAC Guide', subscribers: '95K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Shut off power', body: 'Turn off the disconnect box on the wall next to the outdoor unit, and shut off AC at the thermostat.' },
      { title: 'Remove debris', body: 'Pull grass, leaves, and cottonwood fluff off the fins with your hands or a soft brush.' },
      { title: 'Spray with coil cleaner', body: 'Apply a foaming AC coil cleaner to the fins from the inside out. Let it sit 10 minutes.' },
      { title: 'Rinse gently', body: 'Use a garden hose on a low setting (not a pressure washer — that bends fins). Spray from inside out.' },
      { title: 'Straighten bent fins', body: 'If fins are bent, a fin comb ($8) will straighten them and restore airflow.' },
    ],
    materials: [
      { name: 'AC coil cleaner', price: '$10', affiliate: true },
      { name: 'Fin comb', price: '$8', affiliate: true },
    ],
  },
  {
    slug: 'seal-air-leaks',
    title: 'Seal Air Leaks Around Windows and Doors',
    description: 'Drafts can account for 25% of your heating bill. Caulk and weatherstripping are the cheapest fix in home ownership.',
    category: 'hvac',
    duration: '2 hrs',
    cost: '$20–40',
    difficulty: 'Beginner',
    rating: 4.9,
    reviews: 412,
    premium: false,
    contractorCost: 300,
    diyCost: 30,
    creator: { name: 'This Old House DIY', subscribers: '540K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Find the leaks', body: 'On a windy day, hold a lit incense stick near window and door edges. Smoke movement reveals drafts.' },
      { title: 'Caulk stationary gaps', body: 'Apply a bead of exterior-grade silicone caulk around window frames, siding penetrations, and where trim meets walls.' },
      { title: 'Add weatherstripping to doors', body: 'Install foam or V-strip weatherstripping along the sides and top of door frames. Replace threshold sweeps on the bottom.' },
      { title: 'Insulate outlets on exterior walls', body: 'Pop covers off, tuck in foam gaskets ($4/pack), and replace covers.' },
    ],
    materials: [
      { name: 'Exterior silicone caulk', price: '$8', affiliate: true },
      { name: 'Door weatherstripping kit', price: '$15', affiliate: true },
      { name: 'Outlet gasket pack', price: '$4', affiliate: true },
    ],
  },
  {
    slug: 'refinish-hardwood-floors',
    title: 'Refinish Hardwood Floors',
    description: 'A weekend of work can take 20 years off your floors. Covers sanding, staining, and sealing.',
    category: 'flooring',
    duration: '2–3 days',
    cost: '$150–400',
    difficulty: 'Advanced',
    rating: 4.4,
    reviews: 87,
    premium: true,
    contractorCost: 1800,
    diyCost: 280,
    creator: { name: 'Floors by Matt', subscribers: '88K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Clear the room and prep', body: 'Remove all furniture, rugs, and baseboards. Countersink any protruding nails.' },
      { title: 'Rent a drum sander', body: 'A local equipment rental shop will have one for ~$60/day. Get an edger for $35/day for corners.' },
      { title: 'Sand in three passes', body: 'Start with 36-grit to remove the old finish, then 60-grit, finally 100-grit. Always sand with the grain.' },
      { title: 'Vacuum thoroughly', body: 'Dust will ruin your finish. Vacuum, then tack-cloth the entire floor until a cloth comes up clean.' },
      { title: 'Apply stain (optional)', body: 'If changing color, apply stain with a brush or pad, wipe excess after 5 minutes. Let dry 24 hours.' },
      { title: 'Apply polyurethane', body: 'Apply 3 thin coats of water-based poly with a lambswool applicator. Sand lightly with 220-grit between coats.' },
    ],
    materials: [
      { name: 'Drum sander rental', price: '$60/day', affiliate: false },
      { name: 'Edger rental', price: '$35/day', affiliate: false },
      { name: 'Sandpaper assortment (36, 60, 100 grit)', price: '$40', affiliate: true },
      { name: 'Water-based polyurethane (1 gal)', price: '$55', affiliate: true },
      { name: 'Lambswool applicator + pole', price: '$25', affiliate: true },
    ],
  },
  {
    slug: 'paint-kitchen-cabinets',
    title: 'Paint Kitchen Cabinets',
    description: 'A fraction of the cost of a kitchen remodel and makes an enormous visual impact. Plan for 3–4 days.',
    category: 'painting',
    duration: '3–4 days',
    cost: '$150–250',
    difficulty: 'Intermediate',
    rating: 4.5,
    reviews: 174,
    premium: true,
    contractorCost: 2200,
    diyCost: 190,
    creator: { name: 'Paint Life', subscribers: '210K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Remove doors, drawers, and hardware', body: 'Number every door and hinge with masking tape on the inside so they go back in the same spot.' },
      { title: 'Clean and degrease', body: 'Wipe every surface with TSP or a degreaser. Kitchen grease under old paint causes peeling.' },
      { title: 'Sand lightly', body: 'Use 220-grit sandpaper or a sanding sponge to scuff up the existing finish. Wipe clean.' },
      { title: 'Prime', body: 'Use a bonding primer like Zinsser BIN or Stix. Two thin coats.' },
      { title: 'Paint with cabinet-grade paint', body: 'Benjamin Moore Advance, Sherwin Williams Emerald Urethane, or similar. Two coats with 24-hour dry between.' },
      { title: 'Rehang and reinstall', body: 'Let paint cure at least 48 hours before rehanging doors. Cure fully before heavy use — 2 weeks for durability.' },
    ],
    materials: [
      { name: 'Bonding primer (1 qt)', price: '$20', affiliate: true },
      { name: 'Cabinet-grade paint (1 gal)', price: '$60', affiliate: true },
      { name: '2" angled brush', price: '$14', affiliate: true },
      { name: 'Small foam roller + frame', price: '$12', affiliate: true },
      { name: 'TSP degreaser', price: '$8', affiliate: true },
      { name: 'Sanding sponges (3-pack)', price: '$9', affiliate: true },
    ],
  },
  {
    slug: 'mow-lawn-properly',
    title: 'Mow Your Lawn the Right Way',
    description: 'Most homeowners mow too short and too infrequently. A few changes make your grass thicker and your weeds fewer.',
    category: 'landscaping',
    duration: '30–60 min weekly',
    cost: '$0',
    difficulty: 'Beginner',
    rating: 4.7,
    reviews: 209,
    premium: false,
    contractorCost: 45,
    diyCost: 0,
    creator: { name: 'Lawn & Order', subscribers: '72K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Raise your mower deck', body: 'Cut to 3–3.5" for most cool-season grasses (fescue, Kentucky bluegrass). Warm-season grasses go shorter.' },
      { title: 'Follow the 1/3 rule', body: 'Never cut more than 1/3 of the blade length in a single mow. Long blades stress the plant.' },
      { title: 'Mow dry grass, not wet', body: 'Wet grass clumps, clogs the mower, and tears instead of cutting cleanly.' },
      { title: 'Mulch clippings back in', body: 'Clippings return nitrogen to the soil — free fertilizer. Only bag if the lawn is diseased or overgrown.' },
      { title: 'Alternate your pattern', body: 'Each mow, change direction (N-S, then E-W, then diagonals). Grass "remembers" direction and grows upright.' },
      { title: 'Sharpen the blade each season', body: 'A dull blade tears the grass and turns tips brown. Sharpen or replace every 20–25 hours of use.' },
    ],
    materials: [
      { name: 'Mower blade sharpener file', price: '$12', affiliate: true },
      { name: 'Replacement mower blade', price: '$20', affiliate: true },
    ],
  },
  {
    slug: 'prune-shrubs',
    title: 'Prune Shrubs and Small Trees',
    description: 'Correct pruning shapes, encourages flowering, and prevents pest damage. Timing and tool choice matter more than technique.',
    category: 'landscaping',
    duration: '1–2 hrs',
    cost: '$30–60',
    difficulty: 'Beginner',
    rating: 4.6,
    reviews: 131,
    premium: false,
    contractorCost: 150,
    diyCost: 40,
    creator: { name: 'Lawn & Order', subscribers: '72K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Know when to prune', body: 'Spring-flowering shrubs (lilac, forsythia): prune right after they bloom. Summer bloomers and most others: late winter/early spring while dormant.' },
      { title: 'Remove the "3 D\'s" first', body: 'Dead, diseased, or damaged branches come out first. Cut back to healthy wood or the branch collar.' },
      { title: 'Thin crossing branches', body: 'Branches that rub against each other create wounds and disease entry points. Remove one.' },
      { title: 'Make clean cuts', body: 'Cut just above an outward-facing bud at a 45° angle. Use sharp, clean bypass pruners (not anvil pruners) for live wood.' },
      { title: "Don't over-prune", body: 'Never remove more than 1/3 of a plant in one season. Spread major shaping over 2–3 years.' },
    ],
    materials: [
      { name: 'Bypass pruners', price: '$25', affiliate: true },
      { name: 'Loppers (for branches up to 1.5")', price: '$30', affiliate: true },
      { name: 'Rubbing alcohol (disinfect between plants)', price: '$4', affiliate: true },
    ],
  },
  {
    slug: 'install-baseboards',
    title: 'Install New Baseboards',
    description: 'Upgrade from builder-grade 2" base to tall, detailed trim in a single weekend. Transforms a room.',
    category: 'carpentry',
    duration: '1 day',
    cost: '$80–250',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviews: 167,
    premium: false,
    contractorCost: 650,
    diyCost: 160,
    creator: { name: 'DIY Pete', subscribers: '320K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Remove old baseboards', body: 'Score the top edge with a utility knife to break the paint seal. Pry gently with a flat bar, using a scrap of wood to protect the drywall.' },
      { title: 'Measure each wall', body: 'Measure all walls and add 10% for waste and miter mistakes. Pre-paint baseboards before installing (so much easier).' },
      { title: 'Cut outside corners (mitered)', body: 'Use a miter saw set to 45°. Two pieces meeting at a corner each cut at 45° form a 90° outside corner.' },
      { title: 'Cope inside corners', body: 'For inside corners, cut one piece square against the wall and cope the other piece to fit its profile. Use a coping saw along the painted edge of a 45° cut.' },
      { title: 'Nail with a brad nailer', body: 'Use 18-gauge brads, 2" long, every 16" into studs. Keep nails 1" from the top and bottom edges.' },
      { title: 'Caulk and touch up', body: 'Caulk the top edge and all seams with paintable caulk. Touch up nail holes with spackle, sand, and repaint.' },
    ],
    materials: [
      { name: 'Baseboard molding (measure your linear ft + 10%)', price: '$1.50–5/linear ft', affiliate: true },
      { name: 'Brad nailer (or rental)', price: '$100 (or $25/day rental)', affiliate: true },
      { name: '18-gauge brads (2")', price: '$10', affiliate: true },
      { name: 'Miter saw', price: '$140 (or $35/day rental)', affiliate: true },
      { name: 'Coping saw', price: '$12', affiliate: true },
      { name: 'Paintable caulk', price: '$6', affiliate: true },
    ],
  },
  {
    slug: 'clean-dishwasher',
    title: 'Deep Clean Your Dishwasher',
    description: 'Funky smell? Dishes not drying? A monthly clean keeps your dishwasher running and saves a repair call.',
    category: 'appliances',
    duration: '30 min',
    cost: '$5–10',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 351,
    premium: false,
    contractorCost: 120,
    diyCost: 6,
    creator: { name: 'Appliance Geek', subscribers: '65K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Remove and clean the filter', body: 'The filter is in the bottom of the dishwasher — twist and pull to remove. Rinse under hot water, scrub with an old toothbrush and dish soap.' },
      { title: 'Wipe the door gasket', body: 'Mold and food scum build up in the rubber seal around the door. Wipe with a damp cloth and a dab of dish soap.' },
      { title: 'Clean the spray arms', body: 'Pop off spray arms (usually a twist or pull). Clear clogged holes with a toothpick. Rinse and reinstall.' },
      { title: 'Run a vinegar cycle', body: 'Place 1 cup of white vinegar in a dishwasher-safe bowl on the top rack. Run the hottest cycle with no detergent, empty otherwise.' },
      { title: 'Follow with baking soda', body: 'Sprinkle 1 cup baking soda on the bottom. Run a short hot cycle. Freshens and deodorizes.' },
    ],
    materials: [
      { name: 'White vinegar (1 gal)', price: '$3', affiliate: true },
      { name: 'Baking soda', price: '$2', affiliate: true },
    ],
  },
  {
    slug: 'clean-dryer-vent',
    title: 'Clean Your Dryer Vent',
    description: 'Lint-clogged vents cause 2,900 house fires a year. A yearly clean is the highest-ROI safety task you can do.',
    category: 'appliances',
    duration: '45 min',
    cost: '$20–40',
    difficulty: 'Beginner',
    rating: 4.9,
    reviews: 298,
    premium: false,
    contractorCost: 175,
    diyCost: 30,
    creator: { name: 'Appliance Geek', subscribers: '65K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Unplug the dryer (or cut gas)', body: 'Pull the dryer away from the wall. If gas, shut off the gas valve. If electric, unplug.' },
      { title: 'Disconnect the vent hose', body: 'Loosen the clamp on the vent hose at the back of the dryer and remove the hose from both ends.' },
      { title: 'Vacuum the hose and wall port', body: 'Use a vacuum hose attachment to clean out the flexible hose and the wall port. Scrub stubborn lint with an old toothbrush.' },
      { title: 'Clean the vent run with a brush kit', body: 'A dryer vent brush kit attaches to a drill and pushes through the full duct run. Push from the dryer side out through the exterior vent.' },
      { title: 'Check the exterior vent flap', body: 'Go outside and find the dryer vent exit. Make sure the flapper opens freely and isn\'t blocked by lint or a bird nest.' },
      { title: 'Reconnect and test', body: 'Reattach the hose at both ends, slide the dryer back, restore power/gas, and run a test cycle.' },
    ],
    materials: [
      { name: 'Dryer vent brush kit (works with cordless drill)', price: '$25', affiliate: true },
      { name: 'Vacuum hose adapter', price: '$8', affiliate: true },
    ],
  },
  {
    slug: 'unclog-washer-drain',
    title: 'Fix a Washing Machine That Won\'t Drain',
    description: 'The drain pump filter traps socks, coins, and hair. Clearing it fixes 80% of won\'t-drain errors.',
    category: 'appliances',
    duration: '1 hr',
    cost: '$0–30',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviews: 184,
    premium: true,
    contractorCost: 225,
    diyCost: 10,
    creator: { name: 'Appliance Geek', subscribers: '65K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Unplug and shut off water', body: 'Unplug the washer and close both hot and cold supply valves behind it.' },
      { title: 'Drain residual water', body: 'Most front-loaders have a small drain hose behind a bottom access panel. Put a shallow tray under it, pull it out, and let it drain.' },
      { title: 'Locate the drain pump filter', body: 'Behind the bottom access panel, next to the small drain hose. Have a towel ready — more water will come out.' },
      { title: 'Unscrew and clean the filter', body: 'Twist counter-clockwise to remove. Pull out lint, hair, coins, and debris. Rinse under hot water.' },
      { title: 'Reinstall and test', body: 'Screw the filter back firmly (hand-tight is enough), tuck the drain hose, replace the panel, restore power/water, and run a short cycle.' },
      { title: 'Check the drain hose if still clogged', body: 'If the filter was clean and it still won\'t drain, the drain hose behind the washer may be kinked or clogged. Pull out and rinse with a garden hose.' },
    ],
    materials: [
      { name: 'Shallow drip tray', price: '$8', affiliate: true },
      { name: 'Plumber\'s snake (if hose is clogged)', price: '$22', affiliate: true },
    ],
  },
  {
    slug: 'replace-kitchen-faucet',
    title: 'Replace a Kitchen Faucet',
    description: 'Swap a dated or leaky faucet for a modern pull-down in an afternoon. One of the highest-impact kitchen upgrades for under $200.',
    category: 'plumbing',
    duration: '2–3 hrs',
    cost: '$80–250',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviews: 223,
    premium: true,
    contractorCost: 320,
    diyCost: 150,
    creator: { name: 'Fix It With Rick', subscribers: '240K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Shut off water and disconnect supply lines', body: 'Close both shutoff valves under the sink. Place a bucket underneath. Unscrew hot and cold supply lines from the faucet shanks.' },
      { title: 'Remove the old faucet', body: 'Unscrew the mounting nuts holding the faucet to the sink. A basin wrench is almost required here — regular wrenches can\'t reach behind the sink.' },
      { title: 'Clean the sink deck', body: 'Scrub off old plumbers putty, caulk, or mineral deposits with a scraper and sponge. A clean surface prevents the new faucet from sitting crooked.' },
      { title: 'Mount the new faucet', body: 'Thread the supply lines through the sink hole, drop the faucet in, and tighten the mounting hardware from below. Most modern faucets use a simple threaded nut or bracket.' },
      { title: 'Connect supply lines', body: 'Hand-tighten hot and cold supply lines to the corresponding shutoff valves, then quarter-turn with a wrench. Don\'t overtighten — you\'ll crack the fittings.' },
      { title: 'Turn on and check for leaks', body: 'Open shutoffs slowly. Run hot and cold at full pressure. Dry the connections with a paper towel and check every 10 minutes for an hour.' },
    ],
    materials: [
      { name: 'Kitchen faucet (Delta, Moen, Kohler are solid)', price: '$80–200', affiliate: true },
      { name: 'Basin wrench', price: '$20', affiliate: true },
      { name: 'Braided stainless supply lines', price: '$12 (pair)', affiliate: true },
    ],
  },
  {
    slug: 'install-low-flow-toilet',
    title: 'Install a Low-Flow Toilet',
    description: 'A new 1.28-gallon-per-flush toilet can save 20,000 gallons and $200+ a year. Swap in half a day.',
    category: 'plumbing',
    duration: '3–4 hrs',
    cost: '$150–400',
    difficulty: 'Intermediate',
    rating: 4.5,
    reviews: 178,
    premium: true,
    contractorCost: 450,
    diyCost: 220,
    creator: { name: 'Home Repair Tutor', subscribers: '180K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Shut off water and drain the old toilet', body: 'Close the shutoff valve, flush to empty the tank, then sponge out remaining water. Remove the supply line.' },
      { title: 'Unbolt and remove the old toilet', body: 'Pry off the bolt caps at the base, unscrew the nuts, and rock the toilet side to side to break the wax seal. Lift straight up — it weighs 60–80 lbs.' },
      { title: 'Scrape off the old wax ring', body: 'Use a putty knife to remove every bit of old wax from the flange. Stuff a rag in the drain temporarily so sewer gas doesn\'t come up.' },
      { title: 'Set a new wax ring', body: 'Place the wax ring on the flange (not on the toilet). Remove the rag. Lower the new toilet over the flange bolts and press down evenly.' },
      { title: 'Tighten slowly and evenly', body: 'Alternate between the two flange nuts, snugging each a half-turn at a time. Stop when the toilet doesn\'t rock — overtightening cracks the porcelain.' },
      { title: 'Connect water and test', body: 'Attach the supply line, turn on the water, flush several times, and check for leaks at the base and the tank-to-bowl connection.' },
    ],
    materials: [
      { name: 'Low-flow toilet (1.28 GPF, elongated bowl recommended)', price: '$150–350', affiliate: true },
      { name: 'Wax ring with flange', price: '$6', affiliate: true },
      { name: 'Closet bolts (if not included)', price: '$4', affiliate: true },
    ],
  },
  {
    slug: 'replace-ceiling-light',
    title: 'Replace a Ceiling Light Fixture',
    description: 'Take a boring builder-grade fixture and swap for something you actually like. 45 minutes, one trip to the store.',
    category: 'electrical',
    duration: '45 min',
    cost: '$50–200',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviews: 312,
    premium: false,
    contractorCost: 180,
    diyCost: 90,
    creator: { name: 'Sparky Channel', subscribers: '145K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Kill the breaker', body: 'Turn off the correct circuit breaker. Flip the wall switch to make sure the light goes out. Use a voltage tester at the fixture to confirm.' },
      { title: 'Remove the old fixture', body: 'Unscrew the canopy from the ceiling bracket. Let the fixture hang by the wires while you disconnect them — black to black, white to white, ground to ground.' },
      { title: 'Install the new mounting bracket', body: 'Most new fixtures come with their own bracket. Screw it to the existing ceiling box.' },
      { title: 'Connect wires', body: 'Use wire nuts to join the new fixture\'s wires to the house wires, matching colors. Tuck wires neatly into the box so the canopy sits flush.' },
      { title: 'Mount canopy and install bulbs', body: 'Lift the canopy to the ceiling and screw it in place. Install the bulbs, restore power, and test.' },
    ],
    materials: [
      { name: 'Ceiling light fixture', price: '$40–180', affiliate: true },
      { name: 'Wire nuts', price: '$4', affiliate: true },
      { name: 'Non-contact voltage tester', price: '$18', affiliate: true },
    ],
  },
  {
    slug: 'add-dimmer-switch',
    title: 'Install a Dimmer Switch',
    description: 'Instantly upgrade any room. Works with LED if the dimmer is rated for it. Same wiring as a regular switch, different feel.',
    category: 'electrical',
    duration: '20 min',
    cost: '$15–35',
    difficulty: 'Intermediate',
    rating: 4.8,
    reviews: 267,
    premium: true,
    contractorCost: 140,
    diyCost: 25,
    creator: { name: 'Sparky Channel', subscribers: '145K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Buy an LED-compatible dimmer', body: 'If any bulb on the circuit is LED, get an LED-rated dimmer (Lutron Caseta or similar). Regular dimmers will make LEDs flicker, buzz, or burn out early.' },
      { title: 'Turn off the breaker and verify', body: 'Flip the breaker and confirm dead with a voltage tester on the switch.' },
      { title: 'Photograph the wiring', body: 'Take a clear photo of the existing switch wiring before disconnecting anything. 3-way dimmer installations have more wires — the photo is essential.' },
      { title: 'Disconnect and reconnect per the dimmer instructions', body: 'Each brand wires slightly differently. Most single-pole dimmers use a hot in, hot out, and a ground. Match wire colors per the included diagram.' },
      { title: 'Mount and test', body: 'Screw the dimmer to the box, attach the cover plate, restore power, and test at full brightness and minimum. If bulbs flicker, confirm they\'re dimmable.' },
    ],
    materials: [
      { name: 'LED-rated dimmer switch', price: '$20', affiliate: true },
      { name: 'Non-contact voltage tester', price: '$18', affiliate: true },
    ],
  },
  {
    slug: 'bleed-radiator',
    title: 'Bleed a Hot Water Radiator',
    description: 'Cold spots at the top of a radiator mean trapped air. 2 minutes per radiator restores even heat and cuts fuel bills.',
    category: 'hvac',
    duration: '15 min per system',
    cost: '$5',
    difficulty: 'Beginner',
    rating: 4.9,
    reviews: 156,
    premium: false,
    contractorCost: 90,
    diyCost: 5,
    creator: { name: 'This Old House DIY', subscribers: '540K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Find the bleed valve', body: 'Look at the top side of the radiator for a small square nut or slotted key socket. That\'s the bleed valve.' },
      { title: 'Place a cup under the valve', body: 'Water will come out — have an old cup or rag ready.' },
      { title: 'Open the valve with a key', body: 'Use a radiator bleed key (or flathead screwdriver for some models). Turn counter-clockwise a quarter turn. You\'ll hear a hiss as air escapes.' },
      { title: 'Close when water flows steadily', body: 'Air hisses first, then water starts to drip or stream. As soon as you see steady water with no hissing, close the valve.' },
      { title: 'Repeat for each radiator', body: 'Bleed all radiators in the house, working from the lowest floor up. Then check boiler pressure — it may need topping up after bleeding.' },
    ],
    materials: [
      { name: 'Radiator bleed key (usually universal square socket)', price: '$4', affiliate: true },
    ],
  },
  {
    slug: 'clean-dehumidifier',
    title: 'Clean and Maintain a Dehumidifier',
    description: 'Mold and dust reduce airflow and efficiency. A 20-minute clean every few months extends the unit\'s life by years.',
    category: 'hvac',
    duration: '20 min',
    cost: '$5',
    difficulty: 'Beginner',
    rating: 4.7,
    reviews: 109,
    premium: false,
    contractorCost: 70,
    diyCost: 3,
    creator: { name: 'HVAC Guide', subscribers: '95K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Unplug the unit', body: 'Always cut power before opening any appliance with coils.' },
      { title: 'Empty and wash the bucket', body: 'Pull out the water collection bucket, pour out the water, and wash with warm soapy water. Rinse thoroughly to remove soap residue.' },
      { title: 'Clean the air filter', body: 'Pop out the filter (usually at the back). Vacuum it or rinse in warm water. Let it dry fully before reinstalling.' },
      { title: 'Wipe the coils', body: 'Use a soft brush to gently remove dust from the evaporator coils. Don\'t bend the fins — that kills efficiency.' },
      { title: 'Wipe exterior and reassemble', body: 'Wipe the outside with a damp cloth. Reinstall the clean filter and bucket. Plug in and run.' },
    ],
    materials: [
      { name: 'Mild dish soap', price: '$2', affiliate: false },
      { name: 'Microfiber cloth', price: '$3', affiliate: true },
    ],
  },
  {
    slug: 'repair-tile-grout',
    title: 'Repair Cracked or Missing Tile Grout',
    description: 'Crumbling grout lets water reach the subfloor and causes much bigger damage. Re-grouting a tub surround or floor is a weekend fix anyone can do.',
    category: 'flooring',
    duration: '4–6 hrs + curing',
    cost: '$20–40',
    difficulty: 'Beginner',
    rating: 4.6,
    reviews: 198,
    premium: false,
    contractorCost: 400,
    diyCost: 30,
    creator: { name: 'Floors by Matt', subscribers: '88K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Scrape out old grout', body: 'Use a carbide-tipped grout saw or a rotary tool with a grout bit. Remove at least 2/3 of the depth of the old grout. Vacuum the grout lines clean.' },
      { title: 'Mix new grout', body: 'Mix sanded grout (for joints over 1/8") or unsanded (for thinner joints). Mix to peanut-butter consistency. Let it slake for 10 minutes, then remix briefly.' },
      { title: 'Apply with a rubber float', body: 'Hold the float at a 45° angle and press grout into the joints on the diagonal. Work in 3x3 foot sections so grout doesn\'t dry before you can wipe it.' },
      { title: 'Wipe with a damp sponge', body: 'After ~15 minutes, wipe at a 45° angle across the joints with a barely-damp sponge. Rinse the sponge constantly. Don\'t drag grout out of the joints.' },
      { title: 'Polish the haze after 2 hours', body: 'A thin haze of grout will form on the tile. Buff it off with a dry cloth. Let grout cure 24–72 hours per package instructions before exposure to water.' },
      { title: 'Seal (for cementitious grout)', body: 'Apply a penetrating grout sealer once cured. Prevents staining and mold. Not needed for epoxy grout.' },
    ],
    materials: [
      { name: 'Grout (match existing color as close as possible)', price: '$14', affiliate: true },
      { name: 'Grout saw or rotary tool grout bit', price: '$12', affiliate: true },
      { name: 'Rubber grout float', price: '$10', affiliate: true },
      { name: 'Grout sponge', price: '$6', affiliate: true },
      { name: 'Penetrating grout sealer', price: '$14', affiliate: true },
    ],
  },
  {
    slug: 'deep-clean-carpet',
    title: 'Deep Clean a Carpet',
    description: 'Rental carpet cleaners beat most professional services for a fraction of the cost. 2–3 hours for an average living room.',
    category: 'flooring',
    duration: '2–3 hrs',
    cost: '$40–80',
    difficulty: 'Beginner',
    rating: 4.5,
    reviews: 267,
    premium: false,
    contractorCost: 250,
    diyCost: 55,
    creator: { name: 'DIY Pete', subscribers: '320K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Vacuum thoroughly first', body: 'Any carpet cleaner\'s results depend on how well you vacuum first. Vacuum slowly in overlapping passes. Hit edges and under furniture.' },
      { title: 'Pretreat stains', body: 'Spray pretreatment (or diluted carpet shampoo) on visible stains 10 minutes before cleaning. Work into the fibers with a soft brush.' },
      { title: 'Rent or borrow a carpet cleaner', body: 'Home Depot rents Rug Doctors for ~$35/day. Follow the machine\'s instructions for filling soap and water tanks.' },
      { title: 'Clean in slow, overlapping passes', body: 'Go slow — half the speed of normal vacuuming. After a soap pass, do at least two rinse passes with clean water only to remove residue that attracts dirt.' },
      { title: 'Let carpet dry fully', body: 'Open windows or run fans. Stay off the carpet for 6–24 hours. Walking on wet carpet flattens the fibers.' },
    ],
    materials: [
      { name: 'Carpet cleaner rental (Rug Doctor or similar)', price: '$35/day', affiliate: false },
      { name: 'Carpet shampoo (use with rental)', price: '$18', affiliate: true },
      { name: 'Stain pretreatment spray', price: '$9', affiliate: true },
    ],
  },
  {
    slug: 'paint-front-door',
    title: 'Paint Your Front Door',
    description: 'A bold door color is the cheapest curb-appeal upgrade there is. One Saturday, under $40 in paint.',
    category: 'painting',
    duration: '4–6 hrs + drying',
    cost: '$25–50',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 304,
    premium: false,
    contractorCost: 250,
    diyCost: 40,
    creator: { name: 'Paint Life', subscribers: '210K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Remove or tape off hardware', body: 'Either unscrew the knob, knocker, and kick plate, or mask them with painter\'s tape. Removing takes longer but yields a cleaner finish.' },
      { title: 'Clean and sand lightly', body: 'Wipe the door with a degreaser. Sand lightly with a 220-grit sponge to give the new paint something to grip.' },
      { title: 'Prime any bare spots', body: 'If you\'re going from dark to light, or over stained wood, prime first. Otherwise, direct-to-surface exterior paint is fine.' },
      { title: 'Paint panels first, then stiles and rails', body: 'Paint the recessed panels first with a 2" brush, then the vertical stiles, then the horizontal rails. Two thin coats beat one thick coat.' },
      { title: 'Let cure before closing', body: 'The first few hours of dry time, keep the door propped open. Rehang hardware after 24 hours. Avoid slamming for a week so paint fully cures.' },
    ],
    materials: [
      { name: 'Exterior door paint (1 qt)', price: '$22', affiliate: true },
      { name: '2" angled sash brush', price: '$12', affiliate: true },
      { name: 'Painter\'s tape', price: '$6', affiliate: true },
    ],
  },
  {
    slug: 'overseed-lawn',
    title: 'Overseed a Thin Lawn',
    description: 'Thicker grass crowds out weeds naturally. Overseeding in fall gives you a noticeably better lawn by spring.',
    category: 'landscaping',
    duration: '1 hr + watering for 3 weeks',
    cost: '$30–80',
    difficulty: 'Beginner',
    rating: 4.7,
    reviews: 134,
    premium: false,
    contractorCost: 300,
    diyCost: 60,
    creator: { name: 'Lawn & Order', subscribers: '72K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Time it right', body: 'Cool-season grasses (Kentucky bluegrass, fescue): early fall, 6 weeks before first frost. Warm-season grasses (Bermuda, zoysia): late spring when soil reaches 65°F.' },
      { title: 'Mow short and bag clippings', body: 'Cut the lawn to 2" and bag the clippings. Seed needs to touch soil; long grass blocks contact.' },
      { title: 'Rake and aerate if needed', body: 'Rake up dead thatch. If soil is compacted (common in high-traffic areas), rent a core aerator — it makes a huge difference.' },
      { title: 'Spread the seed', body: 'Use a broadcast spreader and apply at the rate on the bag (usually ~4 lbs per 1,000 sq ft). Walk in two directions — first north-south, then east-west — to avoid stripes.' },
      { title: 'Top-dress lightly with compost', body: 'A 1/4" layer of compost or topsoil holds seed in place and feeds germination.' },
      { title: 'Water daily until established', body: 'Light watering twice a day for the first 2 weeks, then gradually reduce to a normal deep-soak schedule once grass is 2" tall.' },
    ],
    materials: [
      { name: 'Grass seed blend (match your lawn type)', price: '$40', affiliate: true },
      { name: 'Broadcast spreader (or rental)', price: '$35 (or $15/day rental)', affiliate: true },
      { name: 'Compost or topsoil', price: '$20', affiliate: false },
    ],
  },
  {
    slug: 'sharpen-mower-blade',
    title: 'Sharpen a Lawn Mower Blade',
    description: 'A dull blade tears grass instead of cutting. Tips turn brown, fuel use goes up, lawn looks worse. Takes 20 min once a season.',
    category: 'landscaping',
    duration: '20 min',
    cost: '$5–30',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 198,
    premium: false,
    contractorCost: 35,
    diyCost: 8,
    creator: { name: 'Lawn & Order', subscribers: '72K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Disconnect the spark plug', body: 'Pull the rubber boot off the spark plug. Absolutely essential — it prevents the mower from starting if the blade rotates.' },
      { title: 'Drain gas (optional) and tip the mower', body: 'Tip with the carburetor side UP so gas and oil don\'t flood the air filter. Or drain the gas tank first if unsure.' },
      { title: 'Mark the blade orientation', body: 'Mark the bottom-facing side of the blade with a permanent marker before removing. Blades only cut in one orientation.' },
      { title: 'Remove the blade', body: 'Wedge a block of wood between the blade and the deck to stop rotation. Use a socket wrench to remove the center bolt.' },
      { title: 'Sharpen at the original angle', body: 'Use a mill bastard file or bench grinder. Follow the existing bevel angle (usually ~30°). 10–15 strokes per edge is plenty. Don\'t go razor-sharp — butter-knife sharp is correct.' },
      { title: 'Balance the blade', body: 'Hang the blade on a nail through the center hole. If it tips to one side, file that side more until it balances. An unbalanced blade will destroy the mower\'s bearings.' },
      { title: 'Reinstall correctly', body: 'Mount with your mark facing down. Tighten the bolt firmly. Reconnect the spark plug.' },
    ],
    materials: [
      { name: 'Mill bastard file', price: '$8', affiliate: true },
      { name: 'Or bench grinder', price: '$80 (one-time)', affiliate: true },
    ],
  },
  {
    slug: 'install-door-handle-lock',
    title: 'Install a New Door Handle and Deadbolt',
    description: 'Old locks get sticky and aren\'t as secure as modern ones. Replacing is straightforward — 30 minutes per door.',
    category: 'carpentry',
    duration: '30 min',
    cost: '$40–150',
    difficulty: 'Beginner',
    rating: 4.7,
    reviews: 221,
    premium: false,
    contractorCost: 140,
    diyCost: 70,
    creator: { name: 'DIY Pete', subscribers: '320K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Measure before buying', body: 'Measure the backset (distance from door edge to hole center — typically 2-3/8" or 2-3/4"). Measure door thickness too — most locks adjust, but check.' },
      { title: 'Remove the old hardware', body: 'Unscrew the two screws on the interior side. Pull both halves apart. Remove the two screws on the latch plate in the door edge and slide the latch out.' },
      { title: 'Install the new latch', body: 'Slide the new latch into the hole. Orient the sloped face toward the way the door closes. Screw the plate flush with the door edge.' },
      { title: 'Install the handle halves', body: 'Line up the exterior handle with the latch (the square shaft goes through the latch). Hold it in place while you attach the interior half with its two screws.' },
      { title: 'Repeat for deadbolt', body: 'Same process — install the deadbolt latch, then the two halves of the deadbolt. The thumbturn goes on the interior.' },
      { title: 'Test', body: 'Close the door. Handle should turn smoothly; deadbolt should throw freely into the strike plate. If it binds, loosen the screws slightly — you likely overtightened.' },
    ],
    materials: [
      { name: 'Entry handle + deadbolt combo (Kwikset, Schlage)', price: '$60–140', affiliate: true },
      { name: 'Philips screwdriver', price: '$8', affiliate: true },
    ],
  },
  {
    slug: 'hang-heavy-mirror',
    title: 'Hang a Heavy Mirror Securely',
    description: 'Most dropped mirrors land on sheetrock screws with no stud behind them. Do this right and it\'ll hang for decades.',
    category: 'carpentry',
    duration: '30 min',
    cost: '$10–30',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 245,
    premium: false,
    contractorCost: 90,
    diyCost: 15,
    creator: { name: 'DIY Pete', subscribers: '320K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Weigh the mirror', body: 'Under 20 lbs: drywall anchors are fine. 20–50 lbs: one stud minimum. Over 50 lbs: two studs required. A bathroom stand-on scale works for estimation.' },
      { title: 'Find studs', body: 'Use a stud finder along the wall where you want the mirror. Mark stud centers with painter\'s tape at the height you\'ll hang.' },
      { title: 'Choose the right hardware', body: 'Into studs: #10 x 2.5" wood screws. Into drywall only: toggle bolts rated for the weight (never hollow plastic anchors on anything over 15 lbs).' },
      { title: 'Mark the hanger positions', body: 'Measure between the mirror\'s hanging points. Transfer those distances to the wall, keeping level. A piece of painter\'s tape with pencil marks acts as a template.' },
      { title: 'Drill and install', body: 'Drill pilot holes (smaller than your screw). Drive screws until 1/4" protrudes. Lift mirror onto the screws.' },
      { title: 'Level it', body: 'Use a bubble level across the top. If off, slightly adjust one hanger or use a shim.' },
    ],
    materials: [
      { name: 'Stud finder', price: '$20', affiliate: true },
      { name: 'Toggle bolts (rated 50+ lbs)', price: '$7', affiliate: true },
      { name: 'Wood screws (#10 x 2.5")', price: '$4', affiliate: true },
      { name: 'Bubble level', price: '$10', affiliate: true },
    ],
  },
  {
    slug: 'clean-refrigerator-coils',
    title: 'Clean Refrigerator Condenser Coils',
    description: 'Dusty coils make the fridge work twice as hard. A 20-minute clean once a year lowers your electric bill and extends compressor life.',
    category: 'appliances',
    duration: '20 min',
    cost: '$0–15',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 178,
    premium: false,
    contractorCost: 110,
    diyCost: 10,
    creator: { name: 'Appliance Geek', subscribers: '65K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Unplug the fridge', body: 'Pull it forward enough to reach the plug and disconnect.' },
      { title: 'Find the coils', body: 'Most modern fridges have them underneath behind a kick plate. Older models have coils on the back. Pop the kick plate off — usually clipped, sometimes screwed.' },
      { title: 'Vacuum the dust', body: 'Use a vacuum with a brush attachment or a dedicated coil brush. Go slow and catch dust in the vacuum nozzle as you sweep it out.' },
      { title: 'Brush and vacuum fan', body: 'If there\'s a condenser fan visible, brush dust off the blades and vacuum out the compartment.' },
      { title: 'Clean the grille and reassemble', body: 'Wipe the kick plate, snap it back on, push the fridge back in place, plug in.' },
    ],
    materials: [
      { name: 'Coil cleaning brush (long, flexible)', price: '$10', affiliate: true },
    ],
  },
  {
    slug: 'replace-refrigerator-water-filter',
    title: 'Replace a Refrigerator Water Filter',
    description: '6-month job nobody remembers. Old filters grow bacteria and slow water flow to a trickle.',
    category: 'appliances',
    duration: '5 min',
    cost: '$25–60',
    difficulty: 'Beginner',
    rating: 4.9,
    reviews: 298,
    premium: false,
    contractorCost: 0,
    diyCost: 45,
    creator: { name: 'Appliance Geek', subscribers: '65K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Find your filter model', body: 'Check the inside of the fridge or the user manual for the filter model (e.g., Samsung DA29-00020B, Whirlpool EDR3RXD1). Generic aftermarket filters are half the price and work fine.' },
      { title: 'Locate the filter', body: 'Usually top-right inside the fridge, in the ceiling, or at the bottom grille. Depends on model.' },
      { title: 'Remove the old filter', body: 'Turn counter-clockwise 1/4 turn (push-twist design) or press a release button and pull straight out.' },
      { title: 'Install the new filter', body: 'Unwrap the new filter, remove any protective caps, slide it in, and turn clockwise until it locks. You\'ll hear a click.' },
      { title: 'Flush the line', body: 'Run 2–3 gallons through the dispenser to clear trapped air and carbon dust. Water may spurt or come out gray for the first minute — normal.' },
      { title: 'Reset the filter light', body: 'Most fridges have a reset button (often labeled "Filter Reset") — hold for 3 seconds until the indicator turns green.' },
    ],
    materials: [
      { name: 'Replacement filter (match your model)', price: '$30–55', affiliate: true },
    ],
  },
]

export const categories = [
  { id: 'plumbing', name: 'Plumbing', icon: '🚿' },
  { id: 'electrical', name: 'Electrical', icon: '⚡' },
  { id: 'hvac', name: 'HVAC', icon: '🌡️' },
  { id: 'flooring', name: 'Flooring', icon: '🏠' },
  { id: 'painting', name: 'Painting', icon: '🎨' },
  { id: 'landscaping', name: 'Landscaping', icon: '🌿' },
  { id: 'carpentry', name: 'Carpentry', icon: '🔨' },
  { id: 'appliances', name: 'Appliances', icon: '🔧' },
]

export function getGuideBySlug(slug) {
  return guides.find(g => g.slug === slug) ?? null
}

export function getGuidesByCategory(category) {
  return guides.filter(g => g.category === category)
}

export function getFeaturedGuides(count = 6) {
  return guides.filter(g => !g.premium).slice(0, count)
}

export function searchGuides(query) {
  const q = query.toLowerCase()
  return guides.filter(
    g =>
      g.title.toLowerCase().includes(q) ||
      g.description.toLowerCase().includes(q) ||
      g.category.toLowerCase().includes(q)
  )
}
