export const guides = [
  {
    slug: 'fix-leaky-faucet',
    title: 'Fix a Leaky Faucet',
    description: 'Stop that drip and save up to $200/year on your water bill. No plumber needed.',
    category: 'plumbing',
    duration: '45 min',
    cost: '$15–30',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 312,
    premium: false,
    contractorCost: 175,
    diyCost: 22,
    creator: { name: 'Fix It With Rick', subscribers: '240K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Shut off the water supply', body: 'Turn the valves under the sink clockwise until fully closed. Test by turning on the tap — no water should flow.' },
      { title: 'Remove the faucet handle', body: 'Unscrew the decorative cap and the handle screw. Pull the handle straight up to remove.' },
      { title: 'Replace the cartridge or O-rings', body: 'Take the old part to the hardware store to match it. Install the new one in the same orientation.' },
      { title: 'Reassemble and test', body: 'Reverse the disassembly steps, turn the water back on slowly, and check for leaks.' },
    ],
    materials: [
      { name: 'Replacement cartridge', price: '$12–18', affiliate: true },
      { name: 'O-ring kit', price: '$4', affiliate: true },
      { name: 'Adjustable wrench', price: '$14', affiliate: true },
    ],
  },
  {
    slug: 'unclog-drain',
    title: 'Unclog a Slow Drain',
    description: 'Clear hair and soap buildup from bathroom drains in minutes using tools you already have.',
    category: 'plumbing',
    duration: '20 min',
    cost: '$0–10',
    difficulty: 'Beginner',
    rating: 4.7,
    reviews: 518,
    premium: false,
    contractorCost: 120,
    diyCost: 5,
    creator: { name: 'Home Repair Tutor', subscribers: '180K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Remove the drain cover', body: 'Unscrew or pop out the drain stopper. Have a bag ready for debris.' },
      { title: 'Use a drain snake or zip-it tool', body: 'Insert the tool and rotate to catch the clog. Pull out slowly.' },
      { title: 'Flush with hot water', body: 'Run the hottest tap water for 2 minutes to clear residue.' },
    ],
    materials: [
      { name: 'Zip-it drain cleaning tool', price: '$4', affiliate: true },
      { name: 'Rubber gloves', price: '$5', affiliate: true },
    ],
  },
  {
    slug: 'change-furnace-filter',
    title: 'Change Your Furnace Filter',
    description: 'Improve air quality and prevent $500+ HVAC repairs with a 5-minute quarterly task.',
    category: 'hvac',
    duration: '5 min',
    cost: '$10–25',
    difficulty: 'Beginner',
    rating: 4.9,
    reviews: 724,
    premium: false,
    contractorCost: 85,
    diyCost: 15,
    creator: { name: 'HVAC Guide', subscribers: '95K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Find your filter slot', body: 'Usually located on the return air duct or inside the furnace cabinet. Check your manual if unsure.' },
      { title: 'Note the filter size', body: 'Check the edges of the old filter for dimensions (e.g. 16x25x1).' },
      { title: 'Install the new filter', body: 'Slide in with the arrow pointing toward the furnace. Seal the slot closed.' },
    ],
    materials: [
      { name: 'MERV-8 furnace filter (4-pack)', price: '$22', affiliate: true },
    ],
  },
  {
    slug: 'fix-squeaky-floor',
    title: 'Fix a Squeaky Floor',
    description: 'Silence annoying creaks in hardwood or subfloor without removing any boards.',
    category: 'carpentry',
    duration: '30 min',
    cost: '$5–20',
    difficulty: 'Beginner',
    rating: 4.6,
    reviews: 201,
    premium: false,
    contractorCost: 150,
    diyCost: 12,
    creator: { name: 'DIY Pete', subscribers: '320K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Find the squeak', body: 'Walk the area slowly and mark squeaky spots with painter\'s tape.' },
      { title: 'Drive screws through the subfloor', body: 'Use a drill to drive 1.5" drywall screws at an angle into the joist, pulling the subfloor tight.' },
      { title: 'Fill screw holes', body: 'Use wood filler matched to your floor color and sand smooth when dry.' },
    ],
    materials: [
      { name: 'Squeak-Ender kit', price: '$18', affiliate: true },
      { name: 'Wood filler', price: '$7', affiliate: true },
    ],
  },
  {
    slug: 'replace-light-switch',
    title: 'Replace a Light Switch',
    description: 'Swap out a broken or outdated switch in 20 minutes. Covers single-pole and 3-way switches.',
    category: 'electrical',
    duration: '20 min',
    cost: '$5–15',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviews: 389,
    premium: true,
    contractorCost: 130,
    diyCost: 10,
    creator: { name: 'Sparky Channel', subscribers: '145K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Kill the breaker', body: 'Turn off the circuit at your breaker panel. Use a non-contact voltage tester to confirm power is off.' },
      { title: 'Remove the old switch', body: 'Unscrew the cover plate and switch. Take a photo of the wiring before disconnecting.' },
      { title: 'Connect the new switch', body: 'Match wires to the same terminals. Tighten screws firmly.' },
      { title: 'Restore power and test', body: 'Flip the breaker back on and test the switch.' },
    ],
    materials: [
      { name: 'Single-pole switch', price: '$5', affiliate: true },
      { name: 'Non-contact voltage tester', price: '$18', affiliate: true },
      { name: 'Flathead & Phillips screwdrivers', price: '$12', affiliate: true },
    ],
  },
  {
    slug: 'install-laminate-flooring',
    title: 'Install Laminate Flooring',
    description: 'Transform a room with a floating floor installation. No glue, no nails — click-together system.',
    category: 'flooring',
    duration: '1–2 days',
    cost: '$200–600',
    difficulty: 'Intermediate',
    rating: 4.5,
    reviews: 156,
    premium: true,
    contractorCost: 900,
    diyCost: 350,
    creator: { name: 'Floors by Matt', subscribers: '88K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Acclimate the flooring', body: 'Let planks sit in the room for 48 hours so they adjust to temperature and humidity.' },
      { title: 'Prepare the subfloor', body: 'Remove old flooring, fill low spots, and install foam underlayment.' },
      { title: 'Lay the first row', body: 'Start against the longest straight wall, leaving a 1/4" expansion gap.' },
      { title: 'Click and lock rows', body: 'Angle each plank into the previous row and snap down. Stagger end joints by at least 12".' },
      { title: 'Install baseboards', body: 'Cover the expansion gap with baseboards. Do not nail through the flooring.' },
    ],
    materials: [
      { name: 'Laminate flooring (measure your sq ft + 10%)', price: '$1.50–3/sq ft', affiliate: true },
      { name: 'Foam underlayment', price: '$0.25/sq ft', affiliate: true },
      { name: 'Pull bar & tapping block set', price: '$18', affiliate: true },
      { name: 'Spacers', price: '$8', affiliate: true },
    ],
  },
  {
    slug: 'paint-a-room',
    title: 'Paint a Room Like a Pro',
    description: 'Get a smooth, drip-free finish with the right prep, tools, and technique.',
    category: 'painting',
    duration: '1 day',
    cost: '$80–150',
    difficulty: 'Beginner',
    rating: 4.8,
    reviews: 603,
    premium: false,
    contractorCost: 600,
    diyCost: 110,
    creator: { name: 'Paint Life', subscribers: '210K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Prep the room', body: 'Move furniture, remove switch plates, and lay drop cloths.' },
      { title: 'Patch and sand', body: 'Fill nail holes and cracks with spackle. Sand smooth when dry.' },
      { title: "Cut in edges", body: "Use a 2\" angled brush to paint a 3\" border along ceilings, trim, and corners." },
      { title: 'Roll the walls', body: 'Use a 3/8" nap roller in a W pattern, working top to bottom. Apply 2 coats.' },
    ],
    materials: [
      { name: 'Interior paint (1 gal per 350–400 sq ft)', price: '$35–55/gal', affiliate: true },
      { name: '2" angled brush', price: '$12', affiliate: true },
      { name: '3/8" nap roller + frame', price: '$18', affiliate: true },
      { name: "Painter's tape", price: '$8', affiliate: true },
    ],
  },
  {
    slug: 'fix-running-toilet',
    title: 'Fix a Running Toilet',
    description: 'A running toilet wastes 200 gallons a day. Fix it in 30 minutes with a $12 kit.',
    category: 'plumbing',
    duration: '30 min',
    cost: '$12–30',
    difficulty: 'Beginner',
    rating: 4.9,
    reviews: 445,
    premium: false,
    contractorCost: 150,
    diyCost: 20,
    creator: { name: 'Fix It With Rick', subscribers: '240K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Open the tank', body: 'Remove the lid and look inside. The flapper, float, or fill valve is usually the culprit.' },
      { title: 'Check the flapper', body: 'Push down on the flapper. If the running stops, the flapper needs replacing.' },
      { title: 'Replace the flapper', body: 'Unhook the old flapper from the overflow tube ears and snap on the new one.' },
      { title: 'Adjust the float', body: 'The water level should be 1" below the overflow tube. Bend or adjust the float arm.' },
    ],
    materials: [
      { name: 'Universal flapper', price: '$8', affiliate: true },
      { name: 'Fill valve kit', price: '$14', affiliate: true },
    ],
  },
  {
    slug: 'caulk-bathtub',
    title: 'Recaulk a Bathtub',
    description: 'Remove old, moldy caulk and apply a clean bead that lasts years — not months.',
    category: 'plumbing',
    duration: '2 hrs + drying',
    cost: '$15–25',
    difficulty: 'Beginner',
    rating: 4.6,
    reviews: 287,
    premium: false,
    contractorCost: 120,
    diyCost: 18,
    creator: { name: 'Home Repair Tutor', subscribers: '180K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Remove old caulk', body: 'Use a caulk remover tool or utility knife to cut and peel out all old caulk. This takes patience.' },
      { title: 'Clean and dry thoroughly', body: 'Spray with mold-killing cleaner, wipe clean, then wait 24 hours for full drying.' },
      { title: 'Apply new caulk', body: 'Cut the tip at 45°, apply steady pressure in one continuous bead along the joint.' },
      { title: 'Smooth and cure', body: 'Dip a finger in water and run along the bead. Do not use the tub for 24 hours.' },
    ],
    materials: [
      { name: 'Silicone tub & tile caulk', price: '$8', affiliate: true },
      { name: 'Caulk removal tool', price: '$7', affiliate: true },
    ],
  },
  {
    slug: 'install-ceiling-fan',
    title: 'Install a Ceiling Fan',
    description: 'Replace an old light fixture with a ceiling fan. Can cut cooling costs by 30%.',
    category: 'electrical',
    duration: '2 hrs',
    cost: '$80–200',
    difficulty: 'Intermediate',
    rating: 4.5,
    reviews: 198,
    premium: true,
    contractorCost: 250,
    diyCost: 140,
    creator: { name: 'Sparky Channel', subscribers: '145K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Turn off the breaker', body: 'Kill power at the panel and verify with a voltage tester.' },
      { title: 'Remove the old fixture', body: 'Disconnect wires and remove the old box. Install a fan-rated ceiling box.' },
      { title: 'Assemble the fan', body: 'Follow the included instructions. Attach the mounting bracket and canopy.' },
      { title: 'Wire and mount', body: 'Match wire colors (black to black, white to white, ground to green/bare). Snap the canopy up.' },
      { title: 'Attach blades and test', body: 'Install blade brackets and blades. Restore power and test all speeds.' },
    ],
    materials: [
      { name: 'Ceiling fan (your choice)', price: '$60–150', affiliate: true },
      { name: 'Fan-rated ceiling box', price: '$14', affiliate: true },
    ],
  },
  {
    slug: 'winterize-sprinklers',
    title: 'Winterize Your Sprinkler System',
    description: 'Blow out your irrigation lines before the first freeze to avoid cracked pipes.',
    category: 'landscaping',
    duration: '1 hr',
    cost: '$0–30',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviews: 143,
    premium: true,
    contractorCost: 80,
    diyCost: 0,
    creator: { name: 'Lawn & Order', subscribers: '72K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Shut off the water supply', body: 'Close the main irrigation shutoff valve.' },
      { title: 'Rent a compressor', body: 'You need a 20–50 CFM compressor (most home compressors are too small). Many equipment rental shops carry them.' },
      { title: 'Blow out each zone', body: 'Connect to the blow-out port, set controller to Zone 1, and blow for 2 minutes at 50 PSI max.' },
      { title: 'Drain and insulate', body: 'Drain any remaining water and insulate above-ground components.' },
    ],
    materials: [
      { name: 'Compressor rental (or buy an adapter)', price: '$30/day rental', affiliate: false },
      { name: 'Pipe insulation wrap', price: '$8', affiliate: true },
    ],
  },
  {
    slug: 'fix-drywall-hole',
    title: 'Patch a Drywall Hole',
    description: 'Make doorknob holes and other damage disappear with a smooth, paintable patch.',
    category: 'carpentry',
    duration: '2 hrs + drying',
    cost: '$15–30',
    difficulty: 'Beginner',
    rating: 4.7,
    reviews: 334,
    premium: false,
    contractorCost: 140,
    diyCost: 22,
    creator: { name: 'DIY Pete', subscribers: '320K', youtube: 'https://youtube.com' },
    steps: [
      { title: 'Cut a clean opening', body: 'Use a drywall saw to make a square around the damaged area.' },
      { title: 'Add backing', body: 'Cut a piece of wood to span the hole and screw it in from inside.' },
      { title: 'Cut and attach a patch', body: 'Cut a drywall patch to fit, screw to the backing, tape the seams.' },
      { title: 'Apply joint compound', body: 'Skim 3 thin coats, sanding lightly between each. Feather edges wide.' },
    ],
    materials: [
      { name: 'Drywall patch kit', price: '$14', affiliate: true },
      { name: 'Joint compound', price: '$8', affiliate: true },
      { name: 'Drywall tape', price: '$5', affiliate: true },
      { name: 'Sanding sponge', price: '$6', affiliate: true },
    ],
  },
]

export const categories = [
  { id: 'plumbing', name: 'Plumbing', icon: '🚿' },
  { id: 'electrical', name: 'Electrical', icon: '⚡' },
  { id: 'hvac', name: 'HVAC', icon: '🌡️' },
  { id: 'flooring', name: 'Flooring', icon: '🏠' },
  { id: 'painting', name: 'Painting', icon: '🎨' },
  { id: 'landscaping', name: 'Landscaping', icon: '🌿' },
  { id: 'carpentry', name: 'Carpentry', icon: '🔨' },
]

export function getGuideBySlug(slug) {
  return guides.find(g => g.slug === slug) ?? null
}

export function getGuidesByCategory(category) {
  return guides.filter(g => g.category === category)
}

export function getFeaturedGuides(count = 6) {
  return guides.filter(g => !g.premium).slice(0, count)
}

export function searchGuides(query) {
  const q = query.toLowerCase()
  return guides.filter(
    g =>
      g.title.toLowerCase().includes(q) ||
      g.description.toLowerCase().includes(q) ||
      g.category.toLowerCase().includes(q)
  )
}
