// Mock guide data — replace with your database/CMS calls

export const categories = [
  { id: 'plumbing',   name: 'Plumbing',       icon: '🚿' },
  { id: 'hvac',       name: 'HVAC',            icon: '❄️' },
  { id: 'electrical', name: 'Electrical',      icon: '🔌' },
  { id: 'flooring',   name: 'Flooring',        icon: '🪵' },
  { id: 'doors',      name: 'Doors & Windows', icon: '🚪' },
  { id: 'kitchen',    name: 'Kitchen',         icon: '🍳' },
  { id: 'bathroom',   name: 'Bathroom',        icon: '🛁' },
  { id: 'outdoor',    name: 'Outdoor & Deck',  icon: '🌿' },
]

export const guides = [
  {
    id: 'fix-leaky-faucet',
    slug: 'fix-leaky-faucet',
    title: 'How to Fix a Leaky Faucet',
    category: 'plumbing',
    categoryName: 'Plumbing',
    categoryIcon: '🚿',
    difficulty: 'Beginner',
    difficultyColor: 'green',
    time: '30–60 min',
    cost: '$8–$25',
    rating: 4.9,
    ratingCount: 182,
    premium: false,
    description: 'A dripping faucet wastes up to 3,000 gallons per year. This guide walks you through diagnosing and fixing the most common faucet types — no plumber needed.',
    savings: 210,
    creatorName: 'The Plumbing Pro',
    creatorSubs: '214K',
    videoId: 'dQw4w9WgXcQ',
    steps: [
      { title: 'Turn off the water supply', body: 'Find the shut-off valve under the sink and turn clockwise until it stops. Open the faucet to drain remaining pressure.', warning: 'Never skip this step — working on a live line will soak your cabinet instantly.' },
      { title: 'Identify your faucet type', body: 'Check which you have: Ball faucet (one rotating handle), Cartridge faucet (pulls up/down), Ceramic disc, or Compression faucet (two separate handles, older style).', tip: 'Take a photo before disassembling — helps if you need to search for parts later.' },
      { title: 'Remove the handle', body: 'Pop the decorative cap on top of the handle, remove the screw underneath, then gently wiggle the handle off.' },
      { title: 'Remove the cartridge or stem', body: 'Use an adjustable wrench (wrap jaws with tape to protect chrome) to unscrew the packing nut. Pull out the stem or cartridge and note its orientation.', tip: 'Bring the old cartridge to the hardware store — they can match it exactly.' },
      { title: 'Replace the washer, O-ring, or cartridge', body: 'For compression faucets: swap the rubber washer at the bottom of the stem. For cartridge faucets: replace the entire cartridge. Coat new rubber parts with plumber\'s grease before installing.' },
      { title: 'Reassemble and test', body: 'Reverse disassembly steps. Don\'t overtighten — snug is enough. Slowly turn water back on and check for drips at the spout and base.', tip: 'Turn water on slowly — sudden pressure can cause leaks at connections you didn\'t touch.' },
    ],
    materials: [
      { name: 'Adjustable wrench', link: '#', store: 'Amazon' },
      { name: 'Phillips screwdriver', link: '#', store: 'Amazon' },
      { name: 'Flathead screwdriver', link: '#', store: 'Amazon' },
      { name: 'Replacement cartridge / washer kit', link: '#', store: 'Home Depot' },
      { name: "Plumber's grease", link: '#', store: 'Amazon' },
      { name: 'Small bucket or towels', link: null, store: null },
    ],
  },
  {
    id: 'unclog-drain',
    slug: 'unclog-drain',
    title: 'Unclog a Slow Drain Without Chemicals',
    category: 'plumbing',
    categoryName: 'Plumbing',
    categoryIcon: '🚿',
    difficulty: 'Beginner',
    difficultyColor: 'green',
    time: '20 min',
    cost: '$0–$12',
    rating: 4.8,
    ratingCount: 241,
    premium: false,
    description: 'Skip the harsh chemicals. A $5 drain snake and 20 minutes beats Drano every time — and won\'t damage your pipes.',
    savings: 120,
    creatorName: 'The Plumbing Pro',
    creatorSubs: '214K',
    videoId: 'dQw4w9WgXcQ',
    steps: [],
    materials: [],
  },
  {
    id: 'change-furnace-filter',
    slug: 'change-furnace-filter',
    title: 'Change Your Furnace Filter (and Why It Matters)',
    category: 'hvac',
    categoryName: 'HVAC',
    categoryIcon: '❄️',
    difficulty: 'Beginner',
    difficultyColor: 'green',
    time: '10 min',
    cost: '$8–$25',
    rating: 4.9,
    ratingCount: 318,
    premium: true,
    description: 'A dirty filter makes your HVAC work 15% harder and costs you $20–$40/month in extra energy. This takes 10 minutes and should happen every 1–3 months.',
    savings: 480,
    creatorName: 'HVAC Explained',
    creatorSubs: '156K',
    videoId: 'dQw4w9WgXcQ',
    steps: [],
    materials: [],
  },
  {
    id: 'fix-squeaky-floor',
    slug: 'fix-squeaky-floor',
    title: 'Fix a Squeaky Hardwood Floor',
    category: 'flooring',
    categoryName: 'Flooring',
    categoryIcon: '🪵',
    difficulty: 'Beginner',
    difficultyColor: 'green',
    time: '30 min',
    cost: '$0–$15',
    rating: 4.7,
    ratingCount: 95,
    premium: true,
    description: 'That annoying squeak is usually just two boards rubbing together. Fixed permanently in 30 minutes with a $3 bottle of powdered graphite.',
    savings: 180,
    creatorName: 'Home RenoVision DIY',
    creatorSubs: '892K',
    videoId: 'dQw4w9WgXcQ',
    steps: [],
    materials: [],
  },
  {
    id: 'replace-light-switch',
    slug: 'replace-light-switch',
    title: 'Replace a Light Switch Safely',
    category: 'electrical',
    categoryName: 'Electrical',
    categoryIcon: '🔌',
    difficulty: 'Intermediate',
    difficultyColor: 'yellow',
    time: '20 min',
    cost: '$3–$12',
    rating: 4.8,
    ratingCount: 147,
    premium: true,
    description: 'Swapping a switch is one of the easiest electrical jobs — but only if you kill the breaker first. This guide shows you exactly how to do it safely.',
    savings: 95,
    creatorName: 'Safe Wiring Academy',
    creatorSubs: '178K',
    videoId: 'dQw4w9WgXcQ',
    steps: [],
    materials: [],
  },
  {
    id: 'install-laminate-flooring',
    slug: 'install-laminate-flooring',
    title: 'Install Laminate Flooring Start to Finish',
    category: 'flooring',
    categoryName: 'Flooring',
    categoryIcon: '🪵',
    difficulty: 'Intermediate',
    difficultyColor: 'yellow',
    time: 'Full day',
    cost: '$200–$600',
    rating: 4.6,
    ratingCount: 203,
    premium: true,
    description: 'Flooring installers charge $3–$8 per square foot just for labor. A 200 sq ft room DIY saves $600–$1,600. This full-day guide walks you through every step.',
    savings: 1100,
    creatorName: 'Home RenoVision DIY',
    creatorSubs: '892K',
    videoId: 'dQw4w9WgXcQ',
    steps: [],
    materials: [],
  },
]

export function getGuideBySlug(slug) {
  return guides.find(g => g.slug === slug) || null
}

export function getGuidesByCategory(categoryId) {
  return guides.filter(g => g.category === categoryId)
}

export function getFeaturedGuides(limit = 4) {
  return guides.slice(0, limit)
}
